language: generic

sudo: required
services:
  - docker

before_install: 
  - docker build -t tosdan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tosdan/docker-react npm run test

# The test command will force Jest to run in CI-mode, 
# and tests will only run once instead of launching the watcher.
